### PR TITLE
Callback screenshot

### PR DESCRIPTION
**Pull request by jahawkins**
Changed up the callback performed to the team server so that it uses the native CALLBACK_SCREENSHOT, causing the server to populate the screenshot as a Screenshot object. This makes it so that it shows up in the screenshots tab. The Screenshots tab uses Java Swing's ImageIcon class in the JPanel, which doesn't support Bitmap images, only JPG, GIF, and PNG formats.

I created GUI components that will pop up a new tab whenever you receive a new Bitmap screenshot or if you right-click on the screenshot in the Screenshots tab and click "Render BMP"

### CODE REVIEW

**Comment by CodeXTF2** [comment]
this is epic im gonna test this asap and merge if it everything works

**Comment by CodeXTF2** [comment]
Hi, I just tested this and it doesnt work for me. Is there something im doing wrong here?

image

**Comment by jahawkins** [comment]
Ah, sorry, I completely forgot to mention, the Bitmap screenshots can be pretty large (5-7MB in my testing environment), and Cobalt Strike added the TeamServer.props settings to limit large screenshots to prevent DoS attacks against a team server. 

You can fix this by creating a TeamServer.prop file in the same directory as your teamserver. I set mine to:

# ------------------------------------------------
# Validation for screenshot messages from beacons
# ------------------------------------------------
limits.screenshot_validated=true
limits.screenshot_data_maxlen=60211880
# limits.screenshot_user_maxlen=1024
# limits.screenshot_title_maxlen=1024
# Stop writing screenshot data when Disk Usage reaches XX%
# Example: Off
#          "limits.screenshot_diskused_percent=0"
# Example: Stop writing screenshot data when Disk Usage reaches 95%
#          "limits.screenshot_diskused_percent=95"
# Default:
limits.screenshot_diskused_percent=85

That value is like 50MB max size, which is very excessive and I just used for testing. Could probably drop it to about 10MB. I currently don't know of a way to check that value from the CS client GUI, but I could probably figure it out, pass the max size to the BOF, then add logic to download it if above the max size and notify the user around the setting or send to screenshots if below.

**Comment by CodeXTF2** [comment]
Nope. Im on CS4.5 so no max size limit i think.

**Comment by jahawkins** [comment]
Somehow I have 4.2, 4.3, 4.4, and 4.6 as old versions, but not 4.5. I'll test on my end with 4.4 and see if I have any issues and report back.

**Comment by CodeXTF2** [comment]
Ok. i have 4.4 to test with too

**Comment by jahawkins** [comment]
Alright super odd and I got really lucky when building this that I had the right profile set, but this only works when your profile is set to post back data via the URI, not via the post body. This could be a bug in Beacon, I'll ask the HelpSystems team. I tested on 4.4 and got it with the correct profile setup. I'm guessing the post-body is too large and their normal screenshot callback doesn't try to break it up on post-body responses since their screenshots from the built-in are much smaller than from this BOF. They probably still chunk it when it's set to be in the URI due to size, making this work.

So in your profile, for the http-post section for client output, set the data transform to "base64url" then use either "header", "parameter" or "uri-append" as the termination statement. Here is an example of an http-post section that would work:


http-post {
        set uri "/submit.php";
        client {
                header "Content-Type" "application/octet-stream";
                id {
                        parameter "id";
                }
                output {
                        base64url;
                        parameter "test";
                }
        }
        server {
                header "Content-Type" "text/html";
                output {
                        netbiosu;
                        print;
                }
        }
}

**Comment by CodeXTF2** [comment]
ya that would be slow as hell irl tho, due to chunking. i think in its current state i wont merge it yet since it seems a lot more finnicky than the straight up file download (with technically no operational advantage other than convenience) but il def keep it here for now and see if helpsystems fixes it such that this is stable. In the meantime since youve done most of the work already I might as well try working on getting it to encode the hBITMAP into a jpg, which would solve all our problems I think. If I can get that to work then this feature should be perfect. Il work on it when I get some time off schoolwork :D

**Comment by CodeXTF2** [comment]
The other way I can see this working is instead of using beacon screenshot callback we stick with the file download callback, and use the client side code to somehow pull the downloaded bmp from disk and use the BMP renderer you wrote to show it. Not sure if its possible to feed it to the screenshots tab client side, but this is another potentially stable implementation im considering looking into. The advantage of doing the JPG method though would be the smaller filesize to pull over beacon.

**Comment by jahawkins** [comment]
I confirmed that it works if the image is small enough by sending the following BMP data back with the profile using the post body:

char bmp_bmp[] = {
  0x42, 0x4d, 0x1e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1a, 0x00,
  0x00, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00,
  0x18, 0x00, 0x00, 0x00, 0xff, 0x00
};
int bmp_bmp_len = 30;

This is just a 1x1 pixel image to test it out, found from here: https://raw.githubusercontent.com/mathiasbynens/small/master/bmp.bmp

I'll submit it as a feature request for HelpSystems to add chunking to the BeaconOutput when using post body.

It is a little slow, taking about 2-5 minutes to fully upload the screenshot for me.

I looked into JPG and PNG conversions, but I'm terrible at C/C++ and most examples used external libraries which were too difficult for me to incorporate into a BOF correctly. 

As for the download check then image render, that might be possible, i would have to look into how downloads are handled in the client and how accessible that data is.

**Comment by CodeXTF2** [comment]
I guess I can try the first way, im not good at java so you're on your own for the second method if you can find any way to do that. One advantage I see over the second method is that it would backport to the current CS versions, especially if they are trying to take large screenshots. If the bug is due to filesize, then at a certain screen resolution im assuming CS builtin screenshot command will also fail similar to this, due to the filesize. In that case if we implemented it via pulling the downloaded file locally it would work in that very edge case. Gonna test it when I wake up tmw if something like 16k or more resolution breaks beacons builtin screenshot just to confirm that theory if i am able to.

**Comment by jahawkins** [comment]
I'll commit an update to this one shortly. Added a check around the profile to choose where to save it to. If URI param, saves to screenshots, otherwise saves to downloads:

image

Also, added an item to the right-click menu in downloads to render the image as a BMP:

image

This syncs the file down locally to the bin/ folder of the project, then reads the content, renders it in a new GUI tab, then deletes the image from disk.

**Comment by CodeXTF2** [comment]
hmm instead of making it automatic, can it be an optional arg e.g. screenshot_bof screenshot so that they have the option to use either? It can throw an error for now if they choose screenshot and the profile uses post body i guess. I just like the idea of everything being a choice lol

**Comment by CodeXTF2** [comment]
It looks like a nice improvement for now. il check the code and merge it in a bit. il probably change the cna a bit to make the screenshot tab method optional for now until its a bit more stable.

The render BMP option in the downloads tab works nicely.
image

**Comment by CodeXTF2** [comment]
on second thought, if the screenshot doesnt render in the screenshots tab even when sent back, it seem a bit redundant for now + its unstable. Im going to remove the screenshot callback method for now until I find a way to do the JPG compression or when helpsystems fixes the chunking of screenshot callbacks. Just seems more consistent for now. The render BMP button you made should be fine until either of those is fixed.

**Pull request merged**
